Repository gcovr/gcovr, pull requests merged in 2018-02, with the labels that each got.

#211 [Fix #93] --html-detailed triggers html reports by itself
  AUTHORS.txt
  gcovr/tests/bad++char/Makefile
  gcovr/tests/cmake_oos/Makefile
  gcovr/tests/dot/Makefile
  gcovr/tests/excl-branch/Makefile
  gcovr/tests/excl-line/Makefile
  gcovr/tests/filter-test/Makefile
  gcovr/tests/filter-test2/Makefile
  gcovr/tests/linked/Makefile
  gcovr/tests/nested/Makefile
  gcovr/tests/nested2-use-existing/Makefile
  gcovr/tests/nested2/Makefile
  gcovr/tests/nested3/Makefile
  gcovr/tests/nobranch/Makefile
  gcovr/tests/oos/Makefile
  gcovr/tests/oos2/Makefile
  gcovr/tests/shared_lib/Makefile
  gcovr/tests/simple1/Makefile
  gcovr/tests/use-existing/Makefile
  gcovr/tests/wspace/Makefile
  scripts/gcovr
Labels: Format: HTML, Type: Enhancement

#201 Merge commit '03ca8da0' from dev
  scripts/gcovr
Labels: backport-from-dev, needs review

#214 Move script/gcovr to gcovr/__main__.py
  .travis.yml
  gcovr/__main__.py
  gcovr/tests/__init__.py
  gcovr/tests/bad++char/Makefile
  gcovr/tests/cmake_oos/Makefile
  gcovr/tests/dot/Makefile
  gcovr/tests/excl-branch/Makefile
  gcovr/tests/excl-line/Makefile
  gcovr/tests/filter-test/Makefile
  gcovr/tests/filter-test2/Makefile
  gcovr/tests/linked/Makefile
  gcovr/tests/nested/Makefile
  gcovr/tests/nested2-use-existing/Makefile
  gcovr/tests/nested2/Makefile
  gcovr/tests/nested3/Makefile
  gcovr/tests/nobranch/Makefile
  gcovr/tests/oos/Makefile
  gcovr/tests/oos2/Makefile
  gcovr/tests/shared_lib/Makefile
  gcovr/tests/simple1/Makefile
  gcovr/tests/test_gcovr.py
  gcovr/tests/use-existing/Makefile
  gcovr/tests/wspace/Makefile
  setup.cfg
  setup.py
Labels: Type: Enhancement, needs review

#217 Add test for CoverageData update function
  gcovr/tests/update-data/Makefile
  gcovr/tests/update-data/README
  gcovr/tests/update-data/main.cpp
  gcovr/tests/update-data/reference/coverage.html
  gcovr/tests/update-data/reference/coverage.main.cpp.html
  gcovr/tests/update-data/reference/coverage.txt
  gcovr/tests/update-data/reference/coverage.update-data.c.html
  gcovr/tests/update-data/reference/coverage.update-data.h.html
  gcovr/tests/update-data/reference/coverage.xml
  gcovr/tests/update-data/update-data.c
  gcovr/tests/update-data/update-data.h
Labels: Type: Enhancement

#225 Modularization
  CONTRIBUTING.rst
  gcovr/__main__.py
  gcovr/cobertura_xml_generator.py
  gcovr/coverage.py
  gcovr/gcov.py
  gcovr/html_generator.py
  gcovr/summary_generator.py
  gcovr/tests/test_args.py
  gcovr/txt_generator.py
  gcovr/utils.py
  gcovr/version.py
  setup.py
Labels: Type: Enhancement, needs review
