Repository gcovr/gcovr, pull requests merged in 2018-03, with the labels that each got.

#238 Use CXX environment variable in doc/examples tests
  doc/examples/example.sh
  doc/examples/example_branches.sh
  doc/examples/example_html.sh
  doc/examples/example_xml.sh
Labels: Docs, Type: Enhancement

#234 Use Jinja2 templates for HTML generator
  gcovr/html_generator.py
  gcovr/templates/root_page.html
  gcovr/templates/source_page.html
  gcovr/templates/style.css
  setup.py
Labels: Format: HTML, Type: Enhancement, needs review

#247 Fix --print-summary
  AUTHORS.txt
  gcovr/__main__.py
Labels: Format: Text, Type: Bug
