Repository gcovr/gcovr, pull requests merged in 2021-02, with the labels that each got.

#457 Check if issue is mentioned in changelog.
  .github/workflows/deploy.yml
  .github/workflows/test.yml
  CHANGELOG.rst
  CONTRIBUTING.rst
  admin/release_checklist
Labels: Docs, QA, needs review

#445 Run as limited user inside docker
  CHANGELOG.rst
  Makefile
  admin/Dockerfile.qa
  gcovr/tests/test.log
  gcovr/tests/test_args.py
Labels: QA

#443 Move the generators to a sub directory
  CONTRIBUTING.rst
  gcovr/__main__.py
  gcovr/configuration.py
  gcovr/tests/test_html_generator.py
  gcovr/writer/__init__.py
  gcovr/writer/cobertura.py
  gcovr/writer/coveralls.py
  gcovr/writer/csv.py
  gcovr/writer/html.py
  gcovr/writer/json.py
  gcovr/writer/sonarqube.py
  gcovr/writer/summary.py
  gcovr/writer/txt.py
Labels: Internal change

#430 Add option to ignore function coverage
  CHANGELOG.rst
  gcovr/configuration.py
  gcovr/gcov.py
  gcovr/tests/nested3/Makefile
  gcovr/tests/nested3/reference/gcc-5/coverage.file1.cpp.11975e1ce5d9c157e76130f444523bea.html
  gcovr/tests/nested3/reference/gcc-5/coverage.file2.cpp.3545800e72707f891cf27b6eed96d85a.html
  gcovr/tests/nested3/reference/gcc-5/coverage.file3.cpp.bcfa344b5512d8cd5857f2fe86511d71.html
  gcovr/tests/nested3/reference/gcc-5/coverage.file4.cpp.9414ee61cc57b8771eb308d9925280d1.html
  gcovr/tests/nested3/reference/gcc-5/coverage.file5.cpp.4f0be33a4dcfe398ba897b87f58ca7ce.html
  gcovr/tests/nested3/reference/gcc-5/coverage.file6.cpp.521da11c6869ce8705f0ee8a4667568d.html
  gcovr/tests/nested3/reference/gcc-5/coverage.file7.cpp.fa9d180b71a3402bed7d24bb1966eaf5.html
  gcovr/tests/nested3/reference/gcc-5/coverage.html
  gcovr/tests/nested3/reference/gcc-5/coverage.main.cpp.9ddfb860fa969e91a7bb17e903455bce.html
  gcovr/tests/nested3/reference/gcc-5/coverage.txt
  gcovr/tests/nested3/reference/gcc-5/coverage.xml
  gcovr/tests/nested3/reference/gcc-5/coveralls.json
  gcovr/tests/nested3/reference/gcc-5/sonarqube.xml
  gcovr/tests/nested3/reference/gcc-6/coverage.file1.cpp.11975e1ce5d9c157e76130f444523bea.html
  gcovr/tests/nested3/reference/gcc-6/coverage.file2.cpp.3545800e72707f891cf27b6eed96d85a.html
  gcovr/tests/nested3/reference/gcc-6/coverage.file3.cpp.bcfa344b5512d8cd5857f2fe86511d71.html
  gcovr/tests/nested3/reference/gcc-6/coverage.file4.cpp.9414ee61cc57b8771eb308d9925280d1.html
  gcovr/tests/nested3/reference/gcc-6/coverage.file5.cpp.4f0be33a4dcfe398ba897b87f58ca7ce.html
  gcovr/tests/nested3/reference/gcc-6/coverage.file6.cpp.521da11c6869ce8705f0ee8a4667568d.html
  gcovr/tests/nested3/reference/gcc-6/coverage.file7.cpp.fa9d180b71a3402bed7d24bb1966eaf5.html
  gcovr/tests/nested3/reference/gcc-6/coverage.html
  gcovr/tests/nested3/reference/gcc-6/coverage.main.cpp.9ddfb860fa969e91a7bb17e903455bce.html
  gcovr/tests/nested3/reference/gcc-6/coverage.txt
  gcovr/tests/nested3/reference/gcc-6/coverage.xml
  gcovr/tests/nested3/reference/gcc-6/coveralls.json
  gcovr/tests/nested3/reference/gcc-6/sonarqube.xml
  gcovr/tests/nested3/reference/gcc-8/coverage.file1.cpp.11975e1ce5d9c157e76130f444523bea.html
  gcovr/tests/nested3/reference/gcc-8/coverage.file2.cpp.3545800e72707f891cf27b6eed96d85a.html
  gcovr/tests/nested3/reference/gcc-8/coverage.file3.cpp.bcfa344b5512d8cd5857f2fe86511d71.html
  gcovr/tests/nested3/reference/gcc-8/coverage.file4.cpp.9414ee61cc57b8771eb308d9925280d1.html
  gcovr/tests/nested3/reference/gcc-8/coverage.file5.cpp.4f0be33a4dcfe398ba897b87f58ca7ce.html
  gcovr/tests/nested3/reference/gcc-8/coverage.file6.cpp.521da11c6869ce8705f0ee8a4667568d.html
  gcovr/tests/nested3/reference/gcc-8/coverage.file7.cpp.fa9d180b71a3402bed7d24bb1966eaf5.html
  gcovr/tests/nested3/reference/gcc-8/coverage.html
  gcovr/tests/nested3/reference/gcc-8/coverage.main.cpp.9ddfb860fa969e91a7bb17e903455bce.html
  gcovr/tests/nested3/reference/gcc-8/coverage.txt
  gcovr/tests/nested3/reference/gcc-8/coverage.xml
  gcovr/tests/nested3/reference/gcc-8/coveralls.json
  gcovr/tests/nested3/reference/gcc-8/sonarqube.xml
  gcovr/tests/test_gcov_parser.py
Labels: needs review

#470 Drop support for Python 3.5
  CHANGELOG.rst
  doc/source/installation.rst
  setup.py
Labels: Type: Enhancement

#471 Make CI run successfully on all branches
  .github/workflows/test.yml
Labels: QA, Type: Bug
