Repository gcovr/gcovr, pull requests merged in 2021-01, with the labels that each got.

#452 Fix overzealous substitution of root folder
  AUTHORS.txt
  CHANGELOG.rst
  gcovr/__main__.py
Labels: Filters, Type: Bug

#454 Split build and run of Docker container.
  .github/workflows/test.yml
Labels: needs review

#450 Add script for copyright header.
  LICENSE.txt
  README.rst
  admin/add_copyright.py
  doc/examples/test_examples.py
  doc/source/conf.py
  gcovr/__init__.py
  gcovr/__main__.py
  gcovr/cobertura_xml_generator.py
  gcovr/configuration.py
  gcovr/coverage.py
  gcovr/coveralls_generator.py
  gcovr/csv_generator.py
  gcovr/gcov.py
  gcovr/html_generator.py
  gcovr/json_generator.py
  gcovr/sonarqube_generator.py
  gcovr/summary_generator.py
  gcovr/tests/conftest.py
  gcovr/tests/test_args.py
  gcovr/tests/test_config.py
  gcovr/tests/test_gcov_parser.py
  gcovr/tests/test_gcovr.py
  gcovr/tests/test_html_generator.py
  gcovr/txt_generator.py
  gcovr/utils.py
  gcovr/version.py
  gcovr/workers.py
  setup.py
Labels: Docs, needs review
