Repository gcovr/gcovr, pull requests merged in 2022-07, with the labels that each got.

#639 Fix Sphinx generation (language must not be `None`.
  doc/source/conf.py
Labels: Type: Bug, Docs

#616 Forward nox options to call inside docker.
  CHANGELOG.rst
  admin/Dockerfile.qa
  noxfile.py
Labels: Type: Enhancement, QA, Internal change

#642 Fix assert and key error in --decisions flag
  AUTHORS.txt
  CHANGELOG.rst
  gcovr/decision_analysis.py
  gcovr/tests/decisions-neg-delta/Makefile
  gcovr/tests/decisions-neg-delta/README
  gcovr/tests/decisions-neg-delta/main.cpp
  gcovr/tests/decisions-neg-delta/reference/clang-10/coverage.css
  gcovr/tests/decisions-neg-delta/reference/clang-10/coverage.functions.html
  gcovr/tests/decisions-neg-delta/reference/clang-10/coverage.html
  gcovr/tests/decisions-neg-delta/reference/clang-10/coverage.json
  gcovr/tests/decisions-neg-delta/reference/clang-10/coverage.main.cpp.118fcbaaba162ba17933c7893247df3a.html
  gcovr/tests/decisions-neg-delta/reference/clang-13/coverage.functions.html
  gcovr/tests/decisions-neg-delta/reference/clang-13/coverage.json
  gcovr/tests/decisions-neg-delta/reference/clang-13/coverage.main.cpp.118fcbaaba162ba17933c7893247df3a.html
  gcovr/tests/decisions-neg-delta/reference/gcc-11/coverage.functions.html
  gcovr/tests/decisions-neg-delta/reference/gcc-11/coverage.html
  gcovr/tests/decisions-neg-delta/reference/gcc-11/coverage.json
  gcovr/tests/decisions-neg-delta/reference/gcc-11/coverage.main.cpp.118fcbaaba162ba17933c7893247df3a.html
  gcovr/tests/decisions-neg-delta/reference/gcc-5/coverage.css
  gcovr/tests/decisions-neg-delta/reference/gcc-5/coverage.functions.html
  gcovr/tests/decisions-neg-delta/reference/gcc-5/coverage.html
  gcovr/tests/decisions-neg-delta/reference/gcc-5/coverage.json
  gcovr/tests/decisions-neg-delta/reference/gcc-5/coverage.main.cpp.118fcbaaba162ba17933c7893247df3a.html
  gcovr/tests/decisions-neg-delta/reference/gcc-8/coverage.json
  gcovr/tests/decisions-neg-delta/reference/gcc-8/coverage.main.cpp.118fcbaaba162ba17933c7893247df3a.html
Labels: Type: Bug
