Repository gcovr/gcovr, pull requests merged in 2022-03, with the labels that each got.

#569 Fix update of reference data.
  gcovr/tests/test_gcovr.py
Labels: QA, Internal change

#566 Add flake8-print to check usage of print function.
  CHANGELOG.rst
  admin/add_copyright.py
  gcovr/__main__.py
  gcovr/tests/test_gcovr.py
  gcovr/tests/test_html_generator.py
  noxfile.py
Labels: Type: Enhancement, QA, Internal change

#563 Add persisten cache in docker
  .gitignore
  admin/Dockerfile.qa
Labels: QA, Internal change

#565 Don't use realpath in data model, only use them for the filter
  CHANGELOG.rst
  gcovr/gcov.py
  gcovr/tests/simple1-drive-subst/Makefile
  gcovr/tests/simple1-drive-subst/main.cpp
  gcovr/tests/simple1-drive-subst/reference/gcc-8-Windows/coverage-details-linkcss.html
  gcovr/tests/simple1-drive-subst/reference/gcc-8-Windows/coverage-details-linkcss.main.cpp.118fcbaaba162ba17933c7893247df3a.html
  gcovr/tests/simple1-drive-subst/reference/gcc-8-Windows/coverage.json
  gcovr/tests/simple1-drive-subst/reference/gcc-8-Windows/coverage.txt
  gcovr/tests/simple1-drive-subst/reference/gcc-8-Windows/coverage.xml
  gcovr/tests/simple1-drive-subst/reference/gcc-8-Windows/coveralls.json
  gcovr/tests/simple1-drive-subst/reference/gcc-8-Windows/sonarqube.xml
  gcovr/tests/simple1-drive-subst/reference/gcc-8-Windows/summary_coverage.json
  gcovr/tests/test_gcovr.py
  gcovr/utils.py
  noxfile.py
Labels: Type: Enhancement

#571 Fix sanity check in HTML generator.
  CHANGELOG.rst
  gcovr/writer/html.py
Labels: Type: Bug, Format: HTML

#570 Change file level percent values in JSON summary report
  CHANGELOG.rst
  doc/examples/example_json_summary.json
  gcovr/tests/add_coverages/reference/clang-10/summary_coverage.json
  gcovr/tests/add_coverages/reference/gcc-5/summary_coverage.json
  gcovr/tests/add_coverages/reference/gcc-8/summary_coverage.json
  gcovr/tests/bad++char/reference/clang-10/summary_coverage.json
  gcovr/tests/bad++char/reference/gcc-5/summary_coverage.json
  gcovr/tests/bad++char/reference/gcc-8/summary_coverage.json
  gcovr/tests/csv/Makefile
  gcovr/tests/csv/coverage.csv
  gcovr/tests/excl-branch/reference/clang-10/summary_coverage.json
  gcovr/tests/excl-branch/reference/gcc-5/summary_coverage.json
  gcovr/tests/excl-branch/reference/gcc-8/summary_coverage.json
  gcovr/tests/oos/reference/clang-10/summary_coverage.json
  gcovr/tests/oos/reference/gcc-5/summary_coverage.json
  gcovr/tests/oos/reference/gcc-8/summary_coverage.json
  gcovr/tests/simple1-dir/reference/clang-10/summary_coverage.json
  gcovr/tests/simple1-dir/reference/gcc-5/summary_coverage.json
  gcovr/tests/simple1-dir/reference/gcc-8/summary_coverage.json
  gcovr/tests/simple1-drive-subst/reference/gcc-8-Windows/summary_coverage.json
  gcovr/tests/simple1-stdout/reference/clang-10/summary_coverage.json
  gcovr/tests/simple1-stdout/reference/gcc-5/summary_coverage.json
  gcovr/tests/simple1-stdout/reference/gcc-8/summary_coverage.json
  gcovr/tests/simple1/reference/clang-10/summary_coverage.json
  gcovr/tests/simple1/reference/gcc-5/summary_coverage.json
  gcovr/tests/simple1/reference/gcc-8/summary_coverage.json
  gcovr/utils.py
  gcovr/writer/csv.py
  gcovr/writer/json.py
Labels: Type: Bug, Format: JSON

#573 Use last free drive because sometimes C: is used.
  gcovr/tests/test_gcovr.py
Labels: Type: Bug, Platform: Windows, QA, Internal change

#575 Apply review remarks after merge.
  gcovr/tests/test_gcovr.py
Labels: QA, Internal change

#576 directly import Markup from markupsafe (fix breakage with jinja2>=3.1)
  AUTHORS.txt
  CHANGELOG.rst
  gcovr/writer/html.py
Labels: Type: Enhancement, Format: HTML

#555 Rename the sessions for using all compiler versions.
  CHANGELOG.rst
  CONTRIBUTING.rst
  noxfile.py
Labels: Type: Enhancement, QA

#578 Remove leading space in changelog lists.
  CHANGELOG.rst
Labels: Docs, Internal change

#579 Apply black to all files
  CHANGELOG.rst
  doc/examples/test_examples.py
  doc/source/conf.py
  gcovr/__main__.py
  gcovr/coverage.py
  gcovr/tests/conftest.py
  gcovr/tests/test_args.py
  gcovr/tests/test_config.py
  gcovr/tests/test_html_generator.py
  gcovr/utils.py
  gcovr/workers.py
  gcovr/writer/coveralls.py
  gcovr/writer/csv.py
  gcovr/writer/html.py
  gcovr/writer/sonarqube.py
  gcovr/writer/summary.py
  gcovr/writer/txt.py
  noxfile.py
  setup.py
Labels: Type: Enhancement, QA, Internal change

#580 Update docs with new options
  CONTRIBUTING.rst
  doc/source/guide/exclusion-markers.rst
  gcovr/configuration.py
Labels: Docs

#582 Rename add copyright
  admin/bump_version.py
Labels: Type: Enhancement, QA, Internal change

#584 Update references to NEXT version with current version in documentation.
  CHANGELOG.rst
  admin/bump_version.py
  noxfile.py
Labels: Type: Enhancement, Docs, Internal change

#589 Add exception handling for processing of files.
  CHANGELOG.rst
  gcovr/gcov.py
Labels: Type: Enhancement, Gcov

#592 Fix parallel processing of gcov data.
  CHANGELOG.rst
  gcovr/gcov.py
Labels: Type: Bug

#594 Fix black check: Option --check needed.
  CHANGELOG.rst
  admin/bump_version.py
  noxfile.py
Labels: Type: Bug, QA

#593 Add check for required metadata.
  CHANGELOG.rst
  gcovr/gcov_parser.py
Labels: Type: Enhancement

#595 Change black session to reformat files
  CHANGELOG.rst
  CONTRIBUTING.rst
  noxfile.py
Labels: Type: Enhancement, QA, Internal change
