Repository gcovr/gcovr, pull requests merged in 2022-01, with the labels that each got.

#361 Add --no-markers option to ignore exclusion markers
  AUTHORS.txt
  CHANGELOG.rst
  gcovr/configuration.py
  gcovr/gcov.py
  gcovr/gcov_parser.py
  gcovr/tests/no-markers/Makefile
  gcovr/tests/no-markers/main.cpp
  gcovr/tests/no-markers/reference/clang-10/coverage.html
  gcovr/tests/no-markers/reference/clang-10/coverage.json
  gcovr/tests/no-markers/reference/clang-10/coverage.main.cpp.118fcbaaba162ba17933c7893247df3a.html
  gcovr/tests/no-markers/reference/clang-10/coverage.txt
  gcovr/tests/no-markers/reference/clang-10/coverage.xml
  gcovr/tests/no-markers/reference/clang-10/sonarqube.xml
  gcovr/tests/no-markers/reference/gcc-5/coverage.html
  gcovr/tests/no-markers/reference/gcc-5/coverage.json
  gcovr/tests/no-markers/reference/gcc-5/coverage.txt
  gcovr/tests/no-markers/reference/gcc-5/coverage.xml
  gcovr/tests/no-markers/reference/gcc-5/sonarqube.xml
  gcovr/tests/no-markers/reference/gcc-6/coverage.html
  gcovr/tests/no-markers/reference/gcc-6/coverage.json
  gcovr/tests/no-markers/reference/gcc-6/coverage.txt
  gcovr/tests/no-markers/reference/gcc-6/coverage.xml
  gcovr/tests/no-markers/reference/gcc-6/sonarqube.xml
  gcovr/tests/no-markers/reference/gcc-8/coverage.html
  gcovr/tests/no-markers/reference/gcc-8/coverage.json
  gcovr/tests/no-markers/reference/gcc-8/coverage.txt
  gcovr/tests/no-markers/reference/gcc-8/coverage.xml
  gcovr/tests/no-markers/reference/gcc-8/sonarqube.xml
Labels: Type: Enhancement, Filters

#550 Drop support for Python 3.6
  .github/workflows/test.yml
  CHANGELOG.rst
  admin/Dockerfile.qa
  doc/requirements.txt
  doc/source/installation.rst
  setup.py
Labels: Type: Enhancement, QA, dependencies

#558 Fix black check and prepare copyright update
  admin/add_copyright.py
  gcovr/gcov.py
  gcovr/gcov_parser.py
  gcovr/writer/json.py
  noxfile.py
Labels: QA, Internal change

#559 Do not reuse virtual environment.
  noxfile.py
Labels: QA, Internal change

#560 Fix add_copyright.
  admin/add_copyright.py
Labels: QA, Internal change

#564 Pin version of black.
  gcovr/gcov_parser.py
  noxfile.py
Labels: QA, Internal change
