Repository gcovr/gcovr, pull requests merged in 2023-08, with the labels that each got.

#816 Fix reading config files
  CHANGELOG.rst
  gcovr/configuration.py
  gcovr/tests/config-output/Makefile
  gcovr/tests/config-output/config/gcovr.error.config
Labels: Type: Bug, cli

#819 Use `build` instead of calling `setup.py` directly.
  CHANGELOG.rst
  admin/Dockerfile.qa
  noxfile.py
Labels: Internal change

#818 Update html.rst to add --html-theme github.* screenshots
  CHANGELOG.rst
  doc/images/screenshot-html-github-blue-src.png
  doc/images/screenshot-html-github-dark-blue-src.png
  doc/images/screenshot-html-github-dark-green-src.png
  doc/images/screenshot-html-github-green-src.png
  doc/source/output/html.rst
  gcovr/formats/html/github/style.css
  gcovr/tests/html-themes-github/reference/clang-10/coverage.blue.css
  gcovr/tests/html-themes-github/reference/clang-10/coverage.dark-blue.css
  gcovr/tests/html-themes-github/reference/clang-10/coverage.dark-green.css
  gcovr/tests/html-themes-github/reference/clang-10/coverage.green.css
  gcovr/tests/html-themes-github/reference/gcc-5/coverage.blue.css
  gcovr/tests/html-themes-github/reference/gcc-5/coverage.call_decisions.css
  gcovr/tests/html-themes-github/reference/gcc-5/coverage.calls.css
  gcovr/tests/html-themes-github/reference/gcc-5/coverage.dark-blue.css
  gcovr/tests/html-themes-github/reference/gcc-5/coverage.dark-green.css
  gcovr/tests/html-themes-github/reference/gcc-5/coverage.decisions.css
  gcovr/tests/html-themes-github/reference/gcc-5/coverage.green.css
  gcovr/tests/html-themes-github/reference/gcc-5/coverage.legend.css
Labels: Format: HTML, Docs

#824 Update documentation with new entries from #822
  doc/source/output/json.rst
Labels: Docs

#825 Fix Windows test
  gcovr/tests/test_args.py
Labels: QA
