Repository gcovr/gcovr, pull requests merged in 2023-02, with the labels that each got.

#711 Allow annotations for not executed branches.
  CHANGELOG.rst
  gcovr/gcov_parser.py
Labels: Type: Bug, Type: Enhancement, Gcov

#701 Add handling of negative counter
  CHANGELOG.rst
  doc/source/guide.rst
  doc/source/guide/gcov_parser.rst
  gcovr/configuration.py
  gcovr/gcov_parser.py
  gcovr/tests/test_gcov_parser.py
Labels: Type: Enhancement, Gcov

#681 Fix problem with decision parser.
  CHANGELOG.rst
  gcovr/decision_analysis.py
  gcovr/tests/decisions-neg-delta/reference/clang-13/coverage.json
  gcovr/tests/decisions-neg-delta/reference/clang-13/coverage.main.cpp.118fcbaaba162ba17933c7893247df3a.html
  gcovr/tests/decisions-neg-delta/reference/gcc-5/coverage.functions.html
  gcovr/tests/decisions-neg-delta/reference/gcc-5/coverage.html
  gcovr/tests/decisions-neg-delta/reference/gcc-5/coverage.json
  gcovr/tests/decisions-neg-delta/reference/gcc-5/coverage.main.cpp.118fcbaaba162ba17933c7893247df3a.html
  gcovr/tests/decisions-neg-delta/reference/gcc-8/coverage.json
  gcovr/tests/decisions-neg-delta/reference/gcc-8/coverage.main.cpp.118fcbaaba162ba17933c7893247df3a.html
  gcovr/tests/decisions/main.cpp
  gcovr/tests/decisions/reference/clang-10/coverage.functions.html
  gcovr/tests/decisions/reference/clang-10/coverage.html
  gcovr/tests/decisions/reference/clang-10/coverage.json
  gcovr/tests/decisions/reference/clang-10/coverage.main.cpp.118fcbaaba162ba17933c7893247df3a.html
  gcovr/tests/decisions/reference/clang-13/coverage.functions.html
  gcovr/tests/decisions/reference/clang-13/coverage.json
  gcovr/tests/decisions/reference/clang-13/coverage.main.cpp.118fcbaaba162ba17933c7893247df3a.html
  gcovr/tests/decisions/reference/gcc-11/coverage.functions.html
  gcovr/tests/decisions/reference/gcc-11/coverage.html
  gcovr/tests/decisions/reference/gcc-11/coverage.json
  gcovr/tests/decisions/reference/gcc-11/coverage.main.cpp.118fcbaaba162ba17933c7893247df3a.html
  gcovr/tests/decisions/reference/gcc-5/coverage.functions.html
  gcovr/tests/decisions/reference/gcc-5/coverage.html
  gcovr/tests/decisions/reference/gcc-5/coverage.json
  gcovr/tests/decisions/reference/gcc-5/coverage.main.cpp.118fcbaaba162ba17933c7893247df3a.html
  gcovr/tests/decisions/reference/gcc-8/coverage.functions.html
  gcovr/tests/decisions/reference/gcc-8/coverage.html
  gcovr/tests/decisions/reference/gcc-8/coverage.json
  gcovr/tests/decisions/reference/gcc-8/coverage.main.cpp.118fcbaaba162ba17933c7893247df3a.html
Labels: Type: Bug

#717 Add python 3.11 to test matrix
  .github/workflows/test.yml
  CHANGELOG.rst
Labels: QA

#694 Headers containing definitions appear twice in results.
  AUTHORS.txt
  CHANGELOG.rst
  gcovr/gcov.py
  gcovr/tests/test_gcovr.py
  gcovr/tests/wrong-casing/Makefile
  gcovr/tests/wrong-casing/main.case_1
  gcovr/tests/wrong-casing/main.case_2
  gcovr/tests/wrong-casing/reference/gcc-8-Windows/coverage.json
  gcovr/tests/wrong-casing/src/main.cpp
  gcovr/utils.py
Labels: Type: Enhancement, Platform: Windows

#719 Fix deadlog on gcov error
  CHANGELOG.rst
  gcovr/workers.py
Labels: Type: Bug

#718 Abort on processing gcov errors
  CHANGELOG.rst
  gcovr/configuration.py
  gcovr/gcov.py
  gcovr/gcov_parser.py
  gcovr/tests/source_from_pipe/Makefile
  gcovr/tests/test_gcov_parser.py
Labels: Type: Enhancement

#726 Rework exception handling as described in #719
  gcovr/workers.py
Labels: Type: Enhancement

#727 Replace support for keil with documentation entry
  CHANGELOG.rst
  doc/source/cookbook.rst
  gcovr/gcov_parser.py
Labels: Type: Enhancement, Gcov, Docs

#729 Add environment variable to set timestamp
  CHANGELOG.rst
  doc/examples/example_timestamps.sh
  doc/source/guide/timestamps.rst
  gcovr/configuration.py
Labels: Type: Enhancement, Format: HTML, cli, Format: Cobertura, Format: Coveralls

#731 Add clang 14 to test suite
  .github/workflows/test.yml
  CHANGELOG.rst
  CONTRIBUTING.rst
  admin/Dockerfile.qa
  gcovr/tests/simple1/reference/clang-14/fail_under
  gcovr/tests/test_gcovr.py
  noxfile.py
Labels: Type: Enhancement, QA

#737 Update exclusion-markers.rst
  doc/source/guide/exclusion-markers.rst
Labels: Docs
