Repository gcovr/gcovr, pull requests merged in 2023-11, with the labels that each got.

#844 Use options when merging coverage data (#841)
  CHANGELOG.rst
  gcovr/formats/gcov/read.py
  gcovr/merging.py
Labels: Type: Bug, Format: JSON

#845 Remove files added by accident with #839
  decisions-neg-delta/reference/gcc-8-Windows/coverage.main.cpp.118fcbaaba162ba17933c7893247df3a.html
  exclude-throw-branches/reference/gcc-8-Windows/coverage-excl-throw.main.cpp.118fcbaaba162ba17933c7893247df3a.html
  exclude-throw-branches/reference/gcc-8-Windows/coverage-throw.main.cpp.118fcbaaba162ba17933c7893247df3a.html
  html-themes-github/reference/gcc-8-Windows/coverage.call_decisions.main.cpp.118fcbaaba162ba17933c7893247df3a.html
  html-themes-github/reference/gcc-8-Windows/coverage.calls.main.cpp.118fcbaaba162ba17933c7893247df3a.html
  simple1-drive-subst/reference/gcc-8-Windows/coverage-details-linkcss.main.cpp.118fcbaaba162ba17933c7893247df3a.html
  simple1/reference/gcc-8-Windows/coverage-details-includecss.functions.html
  simple1/reference/gcc-8-Windows/coverage-details-includecss.main.cpp.118fcbaaba162ba17933c7893247df3a.html
  simple1/reference/gcc-8-Windows/coverage-details-linkcss.main.cpp.118fcbaaba162ba17933c7893247df3a.html
Labels: Internal change

#846 Clean Lcov and Jacoco output files in tests
  gcovr/tests/exclude-lines-by-pattern/Makefile
  gcovr/tests/exclude-lines-by-pattern/coverage.lcov
  gcovr/tests/linked/Makefile
  gcovr/tests/linked/jacoco.xml
  gcovr/tests/no-markers/Makefile
  gcovr/tests/no-markers/coverage.lcov
  gcovr/tests/noncode/Makefile
  gcovr/tests/noncode/coverage.lcov
  gcovr/tests/simple1-stdout/Makefile
  gcovr/tests/simple1-stdout/coverage.lcov
  gcovr/tests/use-existing/Makefile
  gcovr/tests/use-existing/jacoco.xml
Labels: Internal change

#850 Add support for FIPS enabled OS
  CHANGELOG.rst
  doc/examples/example_csv.csv
  gcovr/formats/coveralls/write.py
  gcovr/formats/gcov/parser.py
  gcovr/formats/html/write.py
  gcovr/formats/lcov/write.py
  gcovr/utils.py
Labels: Type: Enhancement

#853 Add clang 15 to test suite
  .github/workflows/test.yml
  .vscode/tasks.json
  CHANGELOG.rst
  CONTRIBUTING.rst
  gcovr/tests/gcov-ignore_output_error/Makefile
  gcovr/tests/gcov-no_working_dir_found/.gitignore
  gcovr/tests/gcov-no_working_dir_found/Makefile
  gcovr/tests/gcov-no_working_dir_found/reference/clang-10/coverage.json
  gcovr/tests/gcov-no_working_dir_found/reference/gcc-5/coverage.json
  gcovr/tests/gcov-no_working_dir_found/src/main.cpp
  gcovr/tests/simple1/reference/clang-15/fail_under
  gcovr/tests/test_gcovr.py
  noxfile.py
Labels: Type: Enhancement, Platform: macOS, QA

#854 Exclude more test if executed on MacOs
  gcovr/tests/test_gcovr.py
Labels: Platform: macOS, QA, Internal change
