Repository gcovr/gcovr, pull requests merged in 2023-07, with the labels that each got.

#801 Fix Dockerfile.qa to avoid uid conflicts
  CHANGELOG.rst
  admin/Dockerfile.qa
Labels: Type: Bug, QA

#814 Fix substed working dir on windows
  CHANGELOG.rst
  gcovr/__main__.py
  gcovr/coverage.py
  gcovr/formats/gcov/read.py
  gcovr/formats/html/write.py
  gcovr/tests/filter-relative-lib-from-unfiltered-tracefile/Makefile
  gcovr/tests/filter-relative-lib-from-unfiltered-tracefile/setup.cmd
  gcovr/tests/filter-relative-lib/Makefile
  gcovr/tests/filter-relative-lib/setup.cmd
  gcovr/tests/linked/Makefile
  gcovr/tests/linked/setup.cmd
  gcovr/tests/simple1-drive-subst/Makefile
  gcovr/tests/simple1-drive-subst/reference/gcc-8-Windows/coverage-details-linkcss.main.cpp.118fcbaaba162ba17933c7893247df3a.html
  gcovr/tests/simple1-drive-subst/wrap.cmd
  gcovr/tests/symlink-root/Makefile
  gcovr/tests/symlink-root/setup.cmd
  gcovr/utils.py
Labels: Type: Bug, Platform: Windows, QA

#815 Update documentation option --branch
  gcovr/configuration.py
  gcovr/coverage.py
  gcovr/formats/csv/write.py
  gcovr/formats/html/write.py
  gcovr/formats/json/write.py
  gcovr/formats/txt/write.py
Labels: cli
