Repository gcovr/gcovr, pull requests merged in 2023-03, with the labels that each got.

#735 Split templates into one template for each part of each page.
  CHANGELOG.rst
  gcovr/writer/html/templates/directory_page.content.html
  gcovr/writer/html/templates/directory_page.html
  gcovr/writer/html/templates/directory_page.navigation.html
  gcovr/writer/html/templates/directory_page.summary.html
  gcovr/writer/html/templates/functions_page.content.html
  gcovr/writer/html/templates/functions_page.html
  gcovr/writer/html/templates/functions_page.summary.html
  gcovr/writer/html/templates/source_page.content.html
  gcovr/writer/html/templates/source_page.html
  gcovr/writer/html/templates/source_page.navigation.html
  gcovr/writer/html/templates/source_page.summary.html
Labels: Type: Enhancement, Format: HTML

#738 Fix problem in decision parser if case is not on a single line with the break statement.
  CHANGELOG.rst
  gcovr/decision_analysis.py
  gcovr/tests/decisions/main.cpp
  gcovr/tests/decisions/reference/clang-10/coverage.functions.html
  gcovr/tests/decisions/reference/clang-10/coverage.html
  gcovr/tests/decisions/reference/clang-10/coverage.json
  gcovr/tests/decisions/reference/clang-10/coverage.main.cpp.118fcbaaba162ba17933c7893247df3a.html
  gcovr/tests/decisions/reference/clang-13/coverage.functions.html
  gcovr/tests/decisions/reference/clang-13/coverage.json
  gcovr/tests/decisions/reference/clang-13/coverage.main.cpp.118fcbaaba162ba17933c7893247df3a.html
  gcovr/tests/decisions/reference/gcc-11/coverage.functions.html
  gcovr/tests/decisions/reference/gcc-11/coverage.json
  gcovr/tests/decisions/reference/gcc-11/coverage.main.cpp.118fcbaaba162ba17933c7893247df3a.html
  gcovr/tests/decisions/reference/gcc-5/coverage.functions.html
  gcovr/tests/decisions/reference/gcc-5/coverage.html
  gcovr/tests/decisions/reference/gcc-5/coverage.json
  gcovr/tests/decisions/reference/gcc-5/coverage.main.cpp.118fcbaaba162ba17933c7893247df3a.html
  gcovr/tests/decisions/reference/gcc-8/coverage.functions.html
  gcovr/tests/decisions/reference/gcc-8/coverage.json
  gcovr/tests/decisions/reference/gcc-8/coverage.main.cpp.118fcbaaba162ba17933c7893247df3a.html
Labels: Type: Bug

#741 Fix packaging of templates
  .github/workflows/deploy.yml
  noxfile.py
  setup.py
Labels: Type: Bug

#734 Use entrypoint for docker image
  .github/workflows/test.yml
  CHANGELOG.rst
  CONTRIBUTING.rst
  admin/Dockerfile.qa
  doc/requirements.txt
  noxfile.py
Labels: Type: Enhancement, QA, Internal change

#742 Use the rst2html.py again to be able to run the doc for all compilers.
  .github/workflows/test.yml
  noxfile.py
Labels: Type: Bug, Internal change

#712 Do not use realpath for DirectoryPrefixFilter
  CHANGELOG.rst
  gcovr/__main__.py
  gcovr/tests/symlink-root/Makefile
  gcovr/tests/symlink-root/reference/clang-10/coverage.txt
  gcovr/tests/symlink-root/reference/gcc-5/coverage.txt
  gcovr/tests/test_gcovr.py
  gcovr/utils.py
Labels: Type: Enhancement, Filters

#743 Bump version and patch test_example.py. Recreate images.
  .github/workflows/deploy.yml
  CHANGELOG.rst
  LICENSE.txt
  README.rst
  admin/bump_version.py
  doc/examples/example_cobertura.xml
  doc/examples/example_html.details.example.cpp.9597a7a3397b8e3a48116e2a3afb4154.html
  doc/examples/example_html.details.functions.html
  doc/examples/example_html.details.html
  doc/examples/example_html.html
  doc/examples/test_examples.py
  doc/images/screenshot-html-details.example.cpp.png
  doc/images/screenshot-html.png
  doc/source/conf.py
  doc/source/guide/merging.rst
  doc/source/guide/timestamps.rst
  doc/source/output/html.rst
  doc/source/output/json.rst
  gcovr/__init__.py
  gcovr/__main__.py
  gcovr/configuration.py
  gcovr/coverage.py
  gcovr/decision_analysis.py
  gcovr/exclusions/__init__.py
  gcovr/exclusions/markers.py
  gcovr/exclusions/noncode.py
  gcovr/gcov.py
  gcovr/gcov_parser.py
  gcovr/merging.py
  gcovr/tests/conftest.py
  gcovr/tests/test_args.py
  gcovr/tests/test_config.py
  gcovr/tests/test_coverage.py
  gcovr/tests/test_gcov_parser.py
  gcovr/tests/test_gcovr.py
  gcovr/tests/test_html_generator.py
  gcovr/timestamps.py
  gcovr/utils.py
  gcovr/version.py
  gcovr/workers.py
  gcovr/writer/cobertura.py
  gcovr/writer/coveralls.py
  gcovr/writer/csv.py
  gcovr/writer/html/__init__.py
  gcovr/writer/json.py
  gcovr/writer/sonarqube.py
  gcovr/writer/summary.py
  gcovr/writer/txt.py
  noxfile.py
  scripts/pyinstaller_entrypoint.py
  setup.py
Labels: Internal change

#752 Add thread information to logging
  CHANGELOG.rst
  gcovr/__main__.py
  gcovr/utils.py
Labels: Type: Enhancement

#755 Add interface to writer modules
  CHANGELOG.rst
  gcovr/__main__.py
  gcovr/configuration.py
  gcovr/decision_analysis.py
  gcovr/exclusions/__init__.py
  gcovr/exclusions/markers.py
  gcovr/exclusions/noncode.py
  gcovr/formats/__init__.py
  gcovr/formats/base.py
  gcovr/formats/cobertura/__init__.py
  gcovr/formats/cobertura/write.py
  gcovr/formats/coveralls/__init__.py
  gcovr/formats/coveralls/write.py
  gcovr/formats/csv/__init__.py
  gcovr/formats/csv/write.py
  gcovr/formats/gcov/__init__.py
  gcovr/formats/gcov/parser.py
  gcovr/formats/gcov/read.py
  gcovr/formats/gcov/workers.py
  gcovr/formats/html/__init__.py
  gcovr/formats/html/templates/base.html
  gcovr/formats/html/templates/directory_page.content.html
  gcovr/formats/html/templates/directory_page.html
  gcovr/formats/html/templates/directory_page.navigation.html
  gcovr/formats/html/templates/directory_page.summary.html
  gcovr/formats/html/templates/functions_page.content.html
  gcovr/formats/html/templates/functions_page.html
  gcovr/formats/html/templates/functions_page.summary.html
  gcovr/formats/html/templates/source_page.content.html
  gcovr/formats/html/templates/source_page.html
  gcovr/formats/html/templates/source_page.navigation.html
  gcovr/formats/html/templates/source_page.summary.html
  gcovr/formats/html/templates/style.css
  gcovr/formats/html/templates/style.details.css
  gcovr/formats/html/templates/style.filelist.css
  gcovr/formats/html/templates/style.meter.css
  gcovr/formats/html/templates/style.summary.css
  gcovr/formats/html/write.py
  gcovr/formats/json/__init__.py
  gcovr/formats/json/read.py
  gcovr/formats/json/versions.py
  gcovr/formats/json/write.py
  gcovr/formats/sonarqube/__init__.py
  gcovr/formats/sonarqube/write.py
  gcovr/formats/txt/__init__.py
  gcovr/formats/txt/write.py
  gcovr/merging.py
  gcovr/options.py
  gcovr/tests/different-function-lines-separate/Makefile
  gcovr/tests/different-function-lines-use-0/Makefile
  gcovr/tests/test_args.py
  gcovr/tests/test_config.py
  gcovr/tests/test_gcov_parser.py
  gcovr/tests/test_html_generator.py
  gcovr/utils.py
  gcovr/writer/__init__.py
  gcovr/writer/summary.py
  noxfile.py
  setup.py
Labels: Type: Enhancement, Format: Text, Format: HTML, Format: Sonarcube, Format: JSON, Format: Other, Format: CSV, Format: Cobertura, Format: Coveralls
