Repository gcovr/gcovr, pull requests merged in 2024-10, with the labels that each got.

#976 Assume block 0 if block is missing
  CHANGELOG.rst
  gcovr/coverage.py
  gcovr/formats/lcov/write.py
  setup.cfg
  tests/nested2-use-existing/reference/clang-10/coverage.lcov
  tests/nested2-use-existing/reference/gcc-5/coverage.lcov
  tests/nested2-use-existing/reference/gcc-8/coverage.lcov
  tests/use-existing/reference/clang-10/coverage.lcov
  tests/use-existing/reference/clang-13/coverage.lcov
  tests/use-existing/reference/gcc-5/coverage.lcov
  tests/use-existing/reference/gcc-8/coverage.lcov
Labels: Type: Bug, Gcov, Format: LCOV

#980 Remove test on MacOs 12 because of installation issues
  .github/workflows/CI.yml
  CHANGELOG.rst
Labels: QA

#979 Fix KeyError exception for gcc-14
  CHANGELOG.rst
  doc/source/output/json.rst
  gcovr/formats/gcov/read.py
  gcovr/formats/json/read.py
  tests/inline-function/Makefile
  tests/inline-function/main.cpp
  tests/inline-function/reference/clang-10/coverage.functions.html
  tests/inline-function/reference/clang-10/coverage.html
  tests/inline-function/reference/clang-10/coverage.json
  tests/inline-function/reference/clang-10/coverage.main.cpp.118fcbaaba162ba17933c7893247df3a.html
  tests/inline-function/reference/clang-13/coverage.functions.html
  tests/inline-function/reference/clang-13/coverage.json
  tests/inline-function/reference/clang-13/coverage.main.cpp.118fcbaaba162ba17933c7893247df3a.html
  tests/inline-function/reference/gcc-14/coverage.functions.html
  tests/inline-function/reference/gcc-14/coverage.html
  tests/inline-function/reference/gcc-14/coverage.json
  tests/inline-function/reference/gcc-14/coverage.main.cpp.118fcbaaba162ba17933c7893247df3a.html
  tests/inline-function/reference/gcc-5/coverage.functions.html
  tests/inline-function/reference/gcc-5/coverage.html
  tests/inline-function/reference/gcc-5/coverage.json
  tests/inline-function/reference/gcc-5/coverage.main.cpp.118fcbaaba162ba17933c7893247df3a.html
  tests/inline-function/reference/gcc-8/coverage.json
  tests/inline-function/reference/gcc-8/coverage.main.cpp.118fcbaaba162ba17933c7893247df3a.html
  tests/inline-function/reference/gcc-9/coverage.functions.html
  tests/inline-function/reference/gcc-9/coverage.json
  tests/inline-function/reference/gcc-9/coverage.main.cpp.118fcbaaba162ba17933c7893247df3a.html
  tests/test_gcovr.py
Labels: Type: Bug, Gcov

#969 Add test with bazel
  CHANGELOG.rst
  CONTRIBUTING.rst
  admin/Dockerfile.qa
  cspell.json
  gcovr/formats/gcov/read.py
  setup.cfg
  tests/bazel/.bazelrc
  tests/bazel/.gitignore
  tests/bazel/BUILD
  tests/bazel/MODULE.bazel
  tests/bazel/Makefile
  tests/bazel/lib.c
  tests/bazel/lib.h
  tests/bazel/reference/clang-10/coverage.json
  tests/bazel/reference/clang-10/coverage_bazel.json
  tests/bazel/reference/clang-15-Darwin/coverage.json
  tests/bazel/reference/clang-15-Darwin/coverage_bazel.json
  tests/bazel/reference/gcc-14/coverage.json
  tests/bazel/reference/gcc-14/coverage_bazel.json
  tests/bazel/reference/gcc-5/coverage.json
  tests/bazel/reference/gcc-5/coverage_bazel.json
  tests/bazel/reference/gcc-6/coverage.json
  tests/bazel/reference/gcc-6/coverage_bazel.json
  tests/bazel/test/BUILD
  tests/bazel/test/main.c
  tests/test_gcovr.py
Labels: QA

#981 Fix export payload
  noxfile.py
Labels: Docs

#987 Fix access of function coverage list
  CHANGELOG.rst
  gcovr/coverage.py
  gcovr/exclusions/__init__.py
  gcovr/exclusions/utils.py
  noxfile.py
Labels: Type: Bug

#990 Only print info on the first undefined block number in data model
  CHANGELOG.rst
  gcovr/coverage.py
Labels: Type: Enhancement

#991 Exclude also lines belonging to excluded functions
  CHANGELOG.rst
  gcovr/exclusions/__init__.py
Labels: Type: Enhancement

#985 add conditions reporting in --txt-summary
  CHANGELOG.rst
  gcovr/formats/txt/write.py
  tests/decisions/Makefile
  tests/decisions/reference/clang-10/coverage_summary.txt
  tests/decisions/reference/clang-13/coverage_summary.txt
  tests/decisions/reference/clang-15-Darwin/coverage_summary.txt
  tests/decisions/reference/gcc-11/coverage_summary.txt
  tests/decisions/reference/gcc-12/coverage_summary.txt
  tests/decisions/reference/gcc-14/coverage_summary.txt
  tests/decisions/reference/gcc-5/coverage_summary.txt
  tests/decisions/reference/gcc-6/coverage_summary.txt
  tests/decisions/reference/gcc-8/coverage_summary.txt
  tests/print-summary/reference/gcc-14/coverage.txt
Labels: Type: Enhancement, Format: Text

#999 Add file version check for external files
  CHANGELOG.rst
  gcovr/formats/gcov/read.py
Labels: Type: Enhancement, Gcov

#1000 Fix file not found exception
  CHANGELOG.rst
  gcovr/utils.py
Labels: Type: Bug, Platform: Windows

#1001 Support lcov v1 format
  .github/workflows/CI.yml
  .github/workflows/upload_coverage.yml
  CHANGELOG.rst
  gcovr/formats/lcov/__init__.py
  gcovr/formats/lcov/write.py
  tests/nested/Makefile
  tests/nested/reference/clang-10/coverage.lcov
  tests/nested/reference/clang-13/coverage.lcov
  tests/nested/reference/gcc-14/coverage.lcov
  tests/nested/reference/gcc-5/coverage.lcov
  tests/nested/reference/gcc-8/coverage.lcov
Labels: Type: Enhancement, Format: LCOV

#1006 Set the timestamp as environment
  CHANGELOG.rst
  noxfile.py
  setup.py
Labels: Type: Bug

#1003 Upload coverage data of nested testcase
  .github/workflows/CI.yml
  .github/workflows/upload_coverage.yml
Labels: QA

#998 Add empty file coverage
  CHANGELOG.rst
  gcovr/__main__.py
  gcovr/configuration.py
  gcovr/formats/__init__.py
  gcovr/formats/cobertura/read.py
  gcovr/formats/gcov/read.py
  gcovr/formats/json/read.py
  gcovr/utils.py
  tests/include/Makefile
  tests/include/file1.cpp
  tests/include/main.cpp
  tests/include/reference/clang-10/cobertura.xml
  tests/include/reference/clang-10/coverage.css
  tests/include/reference/clang-10/coverage.file1.cpp.37fe642e5aafc503ffc5506444f44c6f.html
  tests/include/reference/clang-10/coverage.html
  tests/include/reference/clang-10/coverage.json
  tests/include/reference/clang-10/coverage.lcov
  tests/include/reference/clang-10/coverage.main.cpp.118fcbaaba162ba17933c7893247df3a.html
  tests/include/reference/clang-10/coverage.txt
  tests/include/reference/clang-10/coveralls.json
  tests/include/reference/clang-10/jacoco.xml
  tests/include/reference/clang-10/sonarqube.xml
  tests/include/reference/clang-13/coverage.json
  tests/include/reference/clang-13/coverage.lcov
  tests/include/reference/clang-13/coverage.main.cpp.118fcbaaba162ba17933c7893247df3a.html
  tests/include/reference/gcc-14/cobertura.xml
  tests/include/reference/gcc-14/coverage.file1.cpp.37fe642e5aafc503ffc5506444f44c6f.html
  tests/include/reference/gcc-14/coverage.functions.html
  tests/include/reference/gcc-14/coverage.html
  tests/include/reference/gcc-14/coverage.json
  tests/include/reference/gcc-14/coverage.lcov
  tests/include/reference/gcc-14/coverage.main.cpp.118fcbaaba162ba17933c7893247df3a.html
  tests/include/reference/gcc-5/cobertura.xml
  tests/include/reference/gcc-5/coverage.css
  tests/include/reference/gcc-5/coverage.file1.cpp.37fe642e5aafc503ffc5506444f44c6f.html
  tests/include/reference/gcc-5/coverage.functions.html
  tests/include/reference/gcc-5/coverage.html
  tests/include/reference/gcc-5/coverage.json
  tests/include/reference/gcc-5/coverage.lcov
  tests/include/reference/gcc-5/coverage.main.cpp.118fcbaaba162ba17933c7893247df3a.html
  tests/include/reference/gcc-5/coverage.txt
  tests/include/reference/gcc-5/coveralls.json
  tests/include/reference/gcc-5/jacoco.xml
  tests/include/reference/gcc-5/sonarqube.xml
  tests/include/reference/gcc-8/cobertura.xml
  tests/include/reference/gcc-8/coverage.functions.html
  tests/include/reference/gcc-8/coverage.html
  tests/include/reference/gcc-8/coverage.json
  tests/include/reference/gcc-8/coverage.lcov
  tests/include/reference/gcc-8/coverage.main.cpp.118fcbaaba162ba17933c7893247df3a.html
  tests/include/reference/gcc-8/coverage.txt
  tests/include/reference/gcc-8/coveralls.json
  tests/include/reference/gcc-8/jacoco.xml
  tests/include/reference/gcc-8/sonarqube.xml
Labels: Type: Enhancement, Gcov

#1004 Add test for MacOs 15
  .github/workflows/CI.yml
  .github/workflows/gcovr-ci-job.yml
  .vscode/tasks.json
  CHANGELOG.rst
  CONTRIBUTING.rst
  noxfile.py
  setup.cfg
  tests/excl-function/reference/clang-16/cobertura.xml
  tests/excl-function/reference/clang-16/coverage.html
  tests/excl-function/reference/clang-16/coverage.json
  tests/excl-function/reference/clang-16/coverage.lcov
  tests/excl-function/reference/clang-16/coverage.main.cpp.118fcbaaba162ba17933c7893247df3a.html
  tests/excl-function/reference/clang-16/coverage.txt
  tests/excl-function/reference/clang-16/coveralls.json
  tests/excl-function/reference/clang-16/jacoco.xml
  tests/excl-function/reference/clang-16/sonarqube.xml
  tests/exclude-throw-branches/reference/clang-16-Darwin/cobertura-excl-throw.xml
  tests/exclude-throw-branches/reference/clang-16-Darwin/cobertura-throw.xml
  tests/exclude-throw-branches/reference/clang-16-Darwin/coverage-excl-throw.json
  tests/exclude-throw-branches/reference/clang-16-Darwin/coverage-excl-throw.main.cpp.118fcbaaba162ba17933c7893247df3a.html
  tests/exclude-throw-branches/reference/clang-16-Darwin/coverage-throw.main.cpp.118fcbaaba162ba17933c7893247df3a.html
  tests/simple1/reference/clang-16/coverage-details-includecss.functions.html
  tests/simple1/reference/clang-16/coverage-details-linkcss.main.cpp.118fcbaaba162ba17933c7893247df3a.html
  tests/simple1/reference/clang-16/fail_under
  tests/test_gcovr.py
Labels: Platform: macOS

#1007 Replace flake8 and black with ruff
  .vscode/tasks.json
  CHANGELOG.rst
  CONTRIBUTING.rst
  admin/Dockerfile.qa
  admin/bump_version.py
  cspell.json
  gcovr/configuration.py
  gcovr/formats/cobertura/read.py
  gcovr/formats/coveralls/write.py
  gcovr/formats/gcov/parser.py
  gcovr/formats/html/write.py
  gcovr/formats/lcov/write.py
  noxfile.py
  pyproject.toml
  setup.cfg
  tests/test_gcov_parser.py
  tests/test_gcovr.py
  tests/test_html_generator.py
Labels: QA

#1013 Update documentation
  CHANGELOG.rst
  CONTRIBUTING.rst
Labels: Docs

#1014 Add pylint and fix issues
  CHANGELOG.rst
  admin/bump_version.py
  cspell.json
  doc/examples/test_examples.py
  doc/source/conf.py
  gcovr/__main__.py
  gcovr/configuration.py
  gcovr/coverage.py
  gcovr/decision_analysis.py
  gcovr/exclusions/utils.py
  gcovr/formats/__init__.py
  gcovr/formats/base.py
  gcovr/formats/clover/__init__.py
  gcovr/formats/clover/write.py
  gcovr/formats/cobertura/__init__.py
  gcovr/formats/cobertura/read.py
  gcovr/formats/cobertura/write.py
  gcovr/formats/coveralls/__init__.py
  gcovr/formats/coveralls/write.py
  gcovr/formats/csv/__init__.py
  gcovr/formats/gcov/__init__.py
  gcovr/formats/gcov/parser.py
  gcovr/formats/gcov/read.py
  gcovr/formats/gcov/workers.py
  gcovr/formats/html/__init__.py
  gcovr/formats/html/write.py
  gcovr/formats/jacoco/__init__.py
  gcovr/formats/jacoco/write.py
  gcovr/formats/json/__init__.py
  gcovr/formats/json/read.py
  gcovr/formats/json/write.py
  gcovr/formats/lcov/__init__.py
  gcovr/formats/sonarqube/__init__.py
  gcovr/formats/sonarqube/write.py
  gcovr/formats/txt/__init__.py
  gcovr/formats/txt/write.py
  gcovr/merging.py
  gcovr/options.py
  gcovr/utils.py
  noxfile.py
  pyproject.toml
  setup.py
  tests/test_args.py
  tests/test_config.py
  tests/test_gcovr.py
Labels: Type: Enhancement, QA

#1015 Align variable names across files
  .github/workflows/CI.yml
  CHANGELOG.rst
  cspell.json
  gcovr/coverage.py
  gcovr/decision_analysis.py
  gcovr/exclusions/__init__.py
  gcovr/exclusions/markers.py
  gcovr/exclusions/utils.py
  gcovr/formats/clover/write.py
  gcovr/formats/cobertura/read.py
  gcovr/formats/cobertura/write.py
  gcovr/formats/coveralls/write.py
  gcovr/formats/gcov/parser.py
  gcovr/formats/html/write.py
  gcovr/formats/jacoco/write.py
  gcovr/formats/json/read.py
  gcovr/formats/json/write.py
  gcovr/formats/lcov/write.py
  gcovr/formats/sonarqube/write.py
  gcovr/formats/txt/write.py
  gcovr/merging.py
  tests/test_args.py
  tests/test_gcov_parser.py
Labels: Internal change
