Repository gcovr/gcovr, pull requests merged in 2024-09, with the labels that each got.

#956 Don't loose stderr and stdout of gcovr for non-zero return code
  CHANGELOG.rst
  gcovr/formats/gcov/read.py
Labels: Type: Bug

#958 Remove codecov
  .github/workflows/upload_coverage.yml
  CHANGELOG.rst
Labels: QA, Internal change

#965 Fix pytest result if coverage is uploaded
  .github/actions/setup-runner/action.yml
  gcovr/formats/gcov/read.py
  noxfile.py
  tests/calls/reference/clang-10/coverage.json
  tests/calls/reference/gcc-14/coverage.json
  tests/gcov-no_working_dir_found/Makefile
  tests/simple1-dir/reference/clang-10/coverage.json
  tests/simple1-dir/reference/gcc-14/coverage.json
  tests/test_gcovr.py
Labels: Type: Bug, QA

#968 Add license type and update documentation
  LICENSE.txt
  README.rst
  admin/bump_version.py
  doc/source/license.rst
Labels: Docs
