Repository gcovr/gcovr, pull requests merged in 2024-01, with the labels that each got.

#867 Add report type enumeration
  CHANGELOG.rst
  gcovr/__main__.py
  gcovr/configuration.py
  gcovr/coverage.py
  gcovr/formats/base.py
  gcovr/formats/csv/write.py
  gcovr/formats/html/write.py
  gcovr/formats/json/write.py
  gcovr/formats/lcov/write.py
  gcovr/formats/txt/__init__.py
  gcovr/formats/txt/write.py
  gcovr/options.py
  gcovr/tests/config-output/Makefile
  gcovr/tests/config-output/config/gcovr.error.config
  gcovr/tests/config-output/config/gcovr.txt-branch.config
  gcovr/tests/sort-percentage/Makefile
  gcovr/tests/sort-uncovered/Makefile
  gcovr/tests/test_args.py
Labels: Type: Enhancement

#869 Drop support for python 3.7
  .github/workflows/deploy.yml
  .github/workflows/test.yml
  CHANGELOG.rst
  admin/Dockerfile.qa
  doc/source/installation.rst
  gcovr/coverage.py
  gcovr/formats/html/write.py
  gcovr/utils.py
  noxfile.py
  setup.cfg
  setup.py
Labels: dependencies

#871 Add configuration for readthedocs
  .readthedocs.yml
Labels: Type: Bug, Docs

#872 Add status badge for documentation
  README.rst
Labels: Type: Enhancement, Docs

#864 [Decisions] Added optional txt-summary print of decision coverage
  CHANGELOG.rst
  gcovr/coverage.py
  gcovr/formats/base.py
  gcovr/formats/gcov/__init__.py
  gcovr/formats/html/__init__.py
  gcovr/formats/txt/__init__.py
  gcovr/formats/txt/write.py
  gcovr/tests/decisions-neg-delta/Makefile
  gcovr/tests/decisions-neg-delta/reference/clang-10/coverage.txt
  gcovr/tests/decisions-neg-delta/reference/gcc-5/coverage.txt
  gcovr/tests/decisions/Makefile
  gcovr/tests/decisions/reference/clang-10/coverage.txt
  gcovr/tests/decisions/reference/gcc-5/coverage.txt
  gcovr/tests/decisions/reference/gcc-6/coverage.txt
  gcovr/tests/decisions/reference/gcc-8/coverage.txt
  gcovr/tests/simple1/reference/clang-10/coverage-details-includecss.functions.html
  gcovr/tests/simple1/reference/clang-10/coverage-details-includecss.main.cpp.118fcbaaba162ba17933c7893247df3a.html
  gcovr/tests/simple1/reference/clang-10/coverage-details-linkcss.functions.html
  gcovr/tests/simple1/reference/clang-10/coverage-details-linkcss.main.cpp.118fcbaaba162ba17933c7893247df3a.html
  gcovr/tests/simple1/reference/clang-13/coverage-details-includecss.functions.html
  gcovr/tests/simple1/reference/clang-13/coverage-details-includecss.main.cpp.118fcbaaba162ba17933c7893247df3a.html
  gcovr/tests/simple1/reference/clang-13/coverage-details-linkcss.functions.html
  gcovr/tests/simple1/reference/clang-13/coverage-details-linkcss.main.cpp.118fcbaaba162ba17933c7893247df3a.html
  gcovr/tests/simple1/reference/gcc-5/coverage-details-includecss.functions.html
  gcovr/tests/simple1/reference/gcc-5/coverage-details-includecss.main.cpp.118fcbaaba162ba17933c7893247df3a.html
  gcovr/tests/simple1/reference/gcc-5/coverage-details-linkcss.functions.html
  gcovr/tests/simple1/reference/gcc-5/coverage-details-linkcss.main.cpp.118fcbaaba162ba17933c7893247df3a.html
  gcovr/tests/simple1/reference/gcc-8/coverage-details-includecss.functions.html
  gcovr/tests/simple1/reference/gcc-8/coverage-details-includecss.main.cpp.118fcbaaba162ba17933c7893247df3a.html
  gcovr/tests/simple1/reference/gcc-8/coverage-details-linkcss.functions.html
  gcovr/tests/simple1/reference/gcc-8/coverage-details-linkcss.main.cpp.118fcbaaba162ba17933c7893247df3a.html
Labels: Type: Enhancement, Format: Text

#858 Prevent Chrome from crashing on large function lists.
  CHANGELOG.rst
  gcovr/formats/html/default/functions_page.content.html
  gcovr/formats/html/github/functions_page.content.html
Labels: Type: Enhancement, Format: HTML

#876 Set version to 7.0+main
  .github/workflows/deploy.yml
  admin/bump_version.py
  doc/examples/example_cobertura.xml
  doc/examples/example_html.details.example.cpp.9597a7a3397b8e3a48116e2a3afb4154.html
  doc/examples/example_html.details.functions.html
  doc/examples/example_html.details.html
  doc/examples/example_html.html
  doc/examples/test_examples.py
  doc/source/conf.py
  gcovr/__init__.py
  gcovr/__main__.py
  gcovr/configuration.py
  gcovr/coverage.py
  gcovr/decision_analysis.py
  gcovr/exclusions/__init__.py
  gcovr/exclusions/markers.py
  gcovr/exclusions/noncode.py
  gcovr/formats/__init__.py
  gcovr/formats/base.py
  gcovr/formats/cobertura/__init__.py
  gcovr/formats/cobertura/read.py
  gcovr/formats/cobertura/write.py
  gcovr/formats/coveralls/__init__.py
  gcovr/formats/coveralls/write.py
  gcovr/formats/csv/__init__.py
  gcovr/formats/csv/write.py
  gcovr/formats/gcov/__init__.py
  gcovr/formats/gcov/parser.py
  gcovr/formats/gcov/read.py
  gcovr/formats/gcov/workers.py
  gcovr/formats/html/__init__.py
  gcovr/formats/html/write.py
  gcovr/formats/jacoco/__init__.py
  gcovr/formats/jacoco/write.py
  gcovr/formats/json/__init__.py
  gcovr/formats/json/read.py
  gcovr/formats/json/versions.py
  gcovr/formats/json/write.py
  gcovr/formats/lcov/__init__.py
  gcovr/formats/lcov/write.py
  gcovr/formats/sonarqube/__init__.py
  gcovr/formats/sonarqube/write.py
  gcovr/formats/txt/__init__.py
  gcovr/formats/txt/write.py
  gcovr/merging.py
  gcovr/options.py
  gcovr/tests/conftest.py
  gcovr/tests/test_args.py
  gcovr/tests/test_config.py
  gcovr/tests/test_coverage.py
  gcovr/tests/test_gcov_parser.py
  gcovr/tests/test_gcovr.py
  gcovr/tests/test_html_generator.py
  gcovr/timestamps.py
  gcovr/utils.py
  gcovr/version.py
  noxfile.py
  scripts/pyinstaller_entrypoint.py
  setup.py
Labels: QA
