Repository gcovr/gcovr, pull requests merged in 2024-08, with the labels that each got.

#941 ✨ Upload standalone applications as release artifacts
  .github/workflows/test.yml
  .gitignore
  CHANGELOG.rst
  noxfile.py
Labels: Type: Enhancement, Platform: Linux, Platform: Windows, Platform: macOS, QA

#946 Use the same workflow for VMs and container check
  .github/actions/setup-python/action.yml
  .github/actions/setup-runner/action.yml
  .github/workflows/deploy.yml
  .github/workflows/gcovr-ci-job.yml
  .github/workflows/test.yml
  .vscode/tasks.json
  CHANGELOG.rst
  noxfile.py
Labels: Type: Enhancement, QA, Internal change

#947 Merge CI and deploy workflow
  .github/workflows/CI.yml
  .github/workflows/deploy.yml
  .github/workflows/gcovr-ci-job.yml
  CHANGELOG.rst
  README.rst
  admin/bump_version.py
  admin/release_checklist.sh
  noxfile.py
Labels: Type: Enhancement, QA, Internal change

#948 Add Codacy to CI
  .github/actions/setup-runner/action.yml
  .github/workflows/CI.yml
  .github/workflows/gcovr-ci-job.yml
  .github/workflows/upload_coverage.yml
  CHANGELOG.rst
  README.rst
  cspell.json
Labels: Type: Enhancement, QA

#949 Add bandit for code checking
  .github/workflows/gcovr-ci-job.yml
  .github/workflows/upload_coverage.yml
  .vscode/tasks.json
  CHANGELOG.rst
  CONTRIBUTING.rst
  admin/bump_version.py
  doc/examples/test_examples.py
  gcovr/configuration.py
  gcovr/coverage.py
  gcovr/formats/clover/write.py
  gcovr/formats/cobertura/read.py
  gcovr/formats/cobertura/write.py
  gcovr/formats/coveralls/write.py
  gcovr/formats/gcov/parser.py
  gcovr/formats/gcov/read.py
  gcovr/formats/gcov/workers.py
  gcovr/formats/html/write.py
  gcovr/formats/jacoco/write.py
  gcovr/formats/json/read.py
  gcovr/formats/sonarqube/write.py
  gcovr/formats/txt/write.py
  gcovr/merging.py
  gcovr/options.py
  gcovr/utils.py
  noxfile.py
  pyproject.toml
  tests/test_gcovr.py
  tests/test_html_generator.py
Labels: QA, Internal change

#950 Fix pylint issues
  .github/workflows/upload_coverage.yml
  gcovr/formats/base.py
  gcovr/formats/clover/__init__.py
  gcovr/formats/cobertura/__init__.py
  gcovr/formats/coveralls/__init__.py
  gcovr/formats/csv/__init__.py
  gcovr/formats/gcov/__init__.py
  gcovr/formats/html/__init__.py
  gcovr/formats/jacoco/__init__.py
  gcovr/formats/json/__init__.py
  gcovr/formats/lcov/__init__.py
  gcovr/formats/sonarqube/__init__.py
  gcovr/formats/txt/__init__.py
Labels: QA

#951 Update status badges
  README.rst
Labels: Docs

#952 Fix semgrep issues
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/general_question.md
  cspell.json
  gcovr/formats/gcov/parser.py
  gcovr/utils.py
  noxfile.py
Labels: Type: Enhancement, QA
